branches:
  except:
  - travis
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy --settings target/travis/settings.xml"
language: java
jdk:
- oraclejdk8
after_success:
- mvn clean test jacoco:report coveralls:report
env:
  global:
  - secure: kFT2MZa8jPlN+Fnu1B8lrcgdDX7FGspNxAUbsSsccBz1Mx5kgh6xkIVZiBvumSYxgJZUo1A5SVrIOQtpFjJVErjIdhDkDzNKo0Fn8OUhHuR/AW3rSLw9nk5JGYukRafLlGBlkcqthVR+6Cu4RAQSS39ybjiUZ8jIiIvmzyD/+syvkLZ2KDvtRqHiyIS0SHiXfK/69TcRbnymrYU7A9BpkdYXWNEhfoDzuisKFTWMHb0R6Fi+db1f2vFeV+/lP2hwee7vMrqV+yF/Y+Gkf7uXObfaTgfV1grc7wniL4uf9N++3yWjMK8e3CpO4VFOC7QQm43QxMsEEdDZCva8koROVBSi6X67hGajTJlSTF9vgUPzxo5rdw8sYlN5BSQookrLUddy7UUfG1XxB6zc+u7Ur78supQzfGy8FDDEmBQtA/7921DGcboqftA+irmyvRrhLjuowsJTqjEYXZiWiy4VpBP6QtBePbdELIbcOs7MVoVp7HMU9+RzK7EvkJo596FlPu5QNoqjMD56jjnGFymT8idM1VBJSkEMIuN4n7wLgSdOLlznpRi74wT6JgFSGY7GhEo0J2H7XZk0jOAEh0pyHkUpuPOtbTpTf2lRyQKnh40O3gJIEwwuGKRb3A3nHONrRiHeitjlwD9D1Fg2XOx6LDMieyNFdYeemIeBG8hIw7U=
  - secure: jSB7Uy0C3yUVuW2ox0JbcE+xlSHK0YFTEpiHE1vvLg/6NM3GJVhbZvBTP/455b4fDAZh7e1RAA1TW6W79epBImM+7ZBGm8ssXuhiJC3cuNaYASCVJqWelJaNGVQ7QDI1rwlfvAsyyEhP9cAEqFrnbxFbXr6qj2+2FHjw4VB1a2YIPTR/zGKZm0RberTjjcjq7jCQPyozav0qEfprzv5BAlQDXFkoyuhsyWSRRuqAd4DNVSucpaYVytDJh8R+8mpkkrM3wcA7eY26ZlKmqad2g+oZuz2C/xtL3DHh4rI0nvm8Duiy5qhmuNSlCYjTuMArkjiEJJpo/yJ0+t151rJymXtwMrMrhimwQadPHLJ//vymgCSg7XyS8clfSbeW805cpkn+PzvT+M9U3V3HOEmqubAoeILHC9uzweUehWhwqRUliAywcY/JgvvEzXdO3q2tYFFIm1lNmjvm6YtCwjxEZrxWODjZnxEhMew5lpYFJFd/fSBGbHqIgSVBvivnYv+h8Hjt0vNqDrh66G7ynJc4XtEMdSFJotaZNR6/PYlPkkvzlGq8KzH27au2FlifUyJZ1azwa0F40fvyg2duYjFD4eUkuEx8ruoWnKjr7fjJ0Ajd8I/Na0nbAFAjL3FhIc3v33HvJMPgcUowD5sZiwIAqSyaKFqK12UPaR4V5QASeWs=
